name: Build
"on":
  pull_request:
    branches: ["main"]
    paths:
      - '**.nix'
      - '**.nu'
      - .github/workflows/build.yaml
      - flake.lock
      - packages/**
  push:
    branches: ["main"]
    paths:
      - '**.nix'
      - '**.nu'
      - .github/workflows/build.yaml
      - flake.lock
      - packages/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - name: Build chapterz
        run: nix build '.#chapterz'
